version: "3"
services:
  git-ci-cd:
    command: npm test
    # command: ${npm_cmd:-"./server && npm test"}
    build:
      args:
        - port=${PORT}
        - env=development
    environment:
      - NODE_ENV=development
    env_file: .env.test
    depends_on:
      - mock-git-server

  mock-git-server:
    container_name: mock-git
    build:
      context: ./git-http-mock-server
    env_file: .env.test
    ports:
      - 8174:8174
    command: ./node_modules/.bin/git-http-mock-server

