version: "3"
services:
  raspberry-ci:
    container_name: node-app
    build: 
      context: ./server
      args:
        - port=${PORT}
        - env=${NODE_ENV:-"production"}
    env_file: .env
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    volumes:
      - ${PROJECT_PATH}:/app/
    # command: npm start
    restart: always
    environment: 
      - DOCKER=true
  mock-git-server:
    container_name: mock-git
    build:
      context: ./git-http-mock-server
    ports:
      - 8174:8174