version: "3"
services:
  raspberry-ci:
    container_name: raspberry-ci
    build: 
      context: .
      args:
        - port=${PORT}
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
    volumes:
      - ${PROJECT_PATH}:/app/${GITHUB_USER}/
