version: "3"
services:
  raspberry-ci:
    container_name: node-app
    build: 
      context: .
      args:
        - port=${PORT}
    env_file: .env
    ports:
      - ${PORT:-4000}:${PORT-4000}
    environment:
      - NODE_ENV=production
    volumes:
      - ${PROJECT_PATH}:/app/${GITHUB_USER}/
