version: '3'
services:
  raspberry-ci:
    container_name: raspberry-ci
    build: .
    env_file: .env
    ports: 
     - 4000:4000
    environment: 
      - NODE_ENV=production
    volumes: 
      - ${PROJECT_PATH}:/app/${GITHUB_USER}/