version: "3"
services:
  raspberry-ci:
    container_name: node-app
    build: 
      context: ./server
      args:
        - port=${PORT}
        - env=${NODE_ENV:-"production"}
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    volumes:
      - ${PROJECT_PATH}:/app/projects/
    command: npm start
