version: "3"
services:
  git-ci-cd:
    build:
      args:
        - port=${PORT}
        - env=development
    environment: 
      - NODE_ENV=development
    volumes:
      - ./server:/app
    command: npm run dev
